package com.hframework.strategy.index.repository;

import com.hframework.strategy.index.repository.indexs.Index;
import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;

import java.util.List;

/**
 * generated by hframework on 2017.
 */@XStreamAlias("indexs")
public class Indexs   {

	@XStreamImplicit
    @XStreamAlias("index")
	private List<Index> indexList;

    public Indexs() {
    }
   
 	 	 
     public List<Index> getIndexList(){
     	return indexList;
     }

     public void setIndexList(List<Index> indexList){
     	this.indexList = indexList;
     }
	 
}
