package com.hframework.strategy.index.repository.indexs;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;
import com.thoughtworks.xstream.annotations.XStreamImplicit;

import java.util.List;

/**
 * generated by hframework on 2017.
 */@XStreamAlias("index")
public class Index   {

	@XStreamImplicit
    @XStreamAlias("hbase")
	private List<Hbase> hbaseList;
	@XStreamImplicit
    @XStreamAlias("mysql")
	private List<Mysql> mysqlList;
    @XStreamImplicit
    @XStreamAlias("redis")
	private List<Redis> redisList;
	@XStreamAsAttribute
    @XStreamAlias("id")
	private String id;
	@XStreamAsAttribute
    @XStreamAlias("name")
	private String name;

    public Index() {
    }
   
 	 	 
     public List<Hbase> getHbaseList(){
     	return hbaseList;
     }

     public void setHbaseList(List<Hbase> hbaseList){
     	this.hbaseList = hbaseList;
     }
	 	 	 
     public List<Mysql> getMysqlList(){
     	return mysqlList;
     }

     public void setMysqlList(List<Mysql> mysqlList){
     	this.mysqlList = mysqlList;
     }

 public List<Redis> getRedisList() {
  return redisList;
 }

 public void setRedisList(List<Redis> redisList) {
  this.redisList = redisList;
 }

 public String getId(){
     	return id;
     }

     public void setId(String id){
     	this.id = id;
     }
	 	 	 
     public String getName(){
     	return name;
     }

     public void setName(String name){
     	this.name = name;
     }
	 
}
