package com.hframework.strategy.index.repository.indexs;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import com.thoughtworks.xstream.annotations.XStreamImplicit;
import com.thoughtworks.xstream.converters.extended.ToAttributedValueConverter;

/**
 * generated by hframework on 2017.
 */@XStreamAlias("mysql")
   @XStreamConverter(value=ToAttributedValueConverter.class, strings={"text"})
public class Mysql   {

	@XStreamAsAttribute
    @XStreamAlias("host")
	private String host;
	@XStreamAsAttribute
    @XStreamAlias("port")
	private String port;
    @XStreamAsAttribute
    @XStreamAlias("database")
    private String database;
    @XStreamAsAttribute
    @XStreamAlias("username")
    private String username;
    @XStreamAsAttribute
    @XStreamAlias("password")
    private String password;
	@XStreamAsAttribute
    @XStreamAlias("table")
	private String table;
	@XStreamAsAttribute
    @XStreamAlias("primary-key")
	private String primaryKey;
	@XStreamAsAttribute
    @XStreamAlias("column")
	private String column;
    private String text;

    public Mysql() {
    }
   
 	 	 
     public String getHost(){
     	return host;
     }

     public void setHost(String host){
     	this.host = host;
     }
	 	 	 
     public String getPort(){
     	return port;
     }

     public void setPort(String port){
     	this.port = port;
     }
	 	 	 
     public String getTable(){
     	return table;
     }

     public void setTable(String table){
     	this.table = table;
     }
	 	 	 
     public String getPrimaryKey(){
     	return primaryKey;
     }

     public void setPrimaryKey(String primaryKey){
     	this.primaryKey = primaryKey;
     }
	 	 	 
     public String getColumn(){
     	return column;
     }

     public void setColumn(String column){
     	this.column = column;
     }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getDatabase() {
        return database;
    }

    public void setDatabase(String database) {
        this.database = database;
    }
}
