package com.hframework.strategy.index.repository.indexs;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;

/**
 * generated by hframework on 2017.
 */@XStreamAlias("redis")
public class Redis   {

	@XStreamAsAttribute
    @XStreamAlias("host")
	private String host;
	@XStreamAsAttribute
    @XStreamAlias("port")
	private String port;
    @XStreamAsAttribute
    @XStreamAlias("db")
    private String db;
	@XStreamAsAttribute
    @XStreamAlias("auth")
	private String auth;
    @XStreamAsAttribute
    @XStreamAlias("key-parts")
    private String keyParts;
    @XStreamAsAttribute
    @XStreamAlias("method")
    private String method;
    @XStreamAsAttribute
    @XStreamAlias("data-type")
    private String dataType;

	@XStreamAsAttribute
    @XStreamAlias("key-converter")
	private String keyConverter;


    public Redis() {
    }
   
 	 	 
     public String getHost(){
     	return host;
     }

     public void setHost(String host){
     	this.host = host;
     }
	 	 	 
     public String getPort(){
     	return port;
     }

     public void setPort(String port){
     	this.port = port;
     }
	 	 	 
     public String getDb(){
     	return db;
     }

     public void setDb(String db){
     	this.db = db;
     }
	 	 	 
     public String getKeyConverter(){
     	return keyConverter;
     }

     public void setKeyConverter(String keyConverter){
     	this.keyConverter = keyConverter;
     }

    public String getKeyParts() {
        return keyParts;
    }

    public void setKeyParts(String keyParts) {
        this.keyParts = keyParts;
    }

    public String getMethod() {
        return method;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public String getDataType() {
        return dataType;
    }

    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    public String getAuth() {
        return auth;
    }

    public void setAuth(String auth) {
        this.auth = auth;
    }
}
