package com.hframework.client.decrypt;

import com.hframework.common.util.message.JsonUtils;
import org.junit.Test;
import com.hframework.client.decrypt.bean.*;

/**
 * generated by hframework on 2018.
 */
public class DecryptClientTest   {

	@Test
	public void des()  throws Exception{
			EncryptResult result =DecryptClient.des("UpaRJY/vC1bbchp4piQ1+A==,q6CWX69KE269ck2g3lk+TQ==,UpaRJY/vC1bbchp4piQ1+A==,");
			System.out.println(result);
			System.out.println(JsonUtils.writeValueAsString(result));
	}

  
 
}
