package com.hframework.strategy.rule.repository.rules;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;

import java.util.List;

/**
 * generated by hframework on 2017.
 */@XStreamAlias("relateRules")
public class RelateRules   {

	@XStreamImplicit
    @XStreamAlias("relateRule")
	private List<RelateRule> relateRuleList;

    public RelateRules() {
    }
   
 	 	 
     public List<RelateRule> getRelateRuleList(){
     	return relateRuleList;
     }

     public void setRelateRuleList(List<RelateRule> relateRuleList){
     	this.relateRuleList = relateRuleList;
     }
	 
}
