package com.hframework.strategy.rule.repository.rules;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;

/**
 * generated by hframework on 2017.
 */@XStreamAlias("relateRule")
public class RelateRule   {

	@XStreamAsAttribute
    @XStreamAlias("code")
	private String code;
	@XStreamAsAttribute
    @XStreamAlias("version")
	private String version;

    public RelateRule() {
    }
   
 	 	 
     public String getCode(){
     	return code;
     }

     public void setCode(String code){
     	this.code = code;
     }
	 	 	 
     public String getVersion(){
     	return version;
     }

     public void setVersion(String version){
     	this.version = version;
     }
	 
}
