package com.hframework.strategy.rule.repository.rules;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;
import com.thoughtworks.xstream.annotations.XStreamImplicit;

import java.util.List;

/**
 * generated by hframework on 2017.
 */@XStreamAlias("rule")
public class Rule   {

    @XStreamAlias("description")
	private String description;
    @XStreamAlias("expression")
	private String expression;
	@XStreamAlias("relateRules")
	private RelateRules relateRules;
	@XStreamAsAttribute
    @XStreamAlias("code")
	private String code;
	@XStreamAsAttribute
    @XStreamAlias("name")
	private String name;
	@XStreamAsAttribute
    @XStreamAlias("version")
	private String version;
	@XStreamAsAttribute
    @XStreamAlias("returnType")
	private String returnType;

    public Rule() {
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getExpression() {
        return expression;
    }

    public void setExpression(String expression) {
        this.expression = expression;
    }

    public RelateRules getRelateRules(){
     	return relateRules;
     }

     public void setRelateRules(RelateRules relateRules){
     	this.relateRules = relateRules;
     }
	 	 	 
     public String getCode(){
     	return code;
     }

     public void setCode(String code){
     	this.code = code;
     }
	 	 	 
     public String getName(){
     	return name;
     }

     public void setName(String name){
     	this.name = name;
     }
	 	 	 
     public String getVersion(){
     	return version;
     }

     public void setVersion(String version){
     	this.version = version;
     }
	 	 	 
     public String getReturnType(){
     	return returnType;
     }

     public void setReturnType(String returnType){
     	this.returnType = returnType;
     }
	 
}
