package com.hframework.client.decrypt.bean;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * generated by hframework on 2018.
 */
public class EncryptResult   {

	@JsonProperty("errorCode")
	private String errorCode;
	@JsonProperty("errorMsg")
	private String errorMsg;
	@JsonProperty("data")
	private String data;
	
	private boolean converted;

    public EncryptResult() {
    }
 	
	public EncryptResult convert()  throws Exception{
			return this;
	}

  
 	 	 
     public String getErrorCode(){
     	return errorCode;
     }

     public void setErrorCode(String errorCode){
     	this.errorCode = errorCode;
     }
	 	 	 
     public String getErrorMsg(){
     	return errorMsg;
     }

     public void setErrorMsg(String errorMsg){
     	this.errorMsg = errorMsg;
     }
	 	 	 
     public String getData(){
     	return data;
     }

     public void setData(String data){
     	this.data = data;
     }
	 	 
}
