package com.hframework.smartweb.bean;

import com.hframework.smartweb.bean.apiconf.*;
import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;
import com.thoughtworks.xstream.annotations.XStreamImplicit;

import java.util.List;

/**
 * generated by hframework on 2017.
 */@XStreamAlias("api")
public class ApiConf   {

	@XStreamAlias("parameters")
	private Parameters parameters;
	@XStreamImplicit
    @XStreamAlias("prehandler")
	private List<Handler> prehandlerList;
	@XStreamImplicit
    @XStreamAlias("precheck")
	private List<Precheck> precheckList;
	@XStreamAlias("handlers")
	private Handlers handlers;
	@XStreamAlias("results")
	private Results results;
	@XStreamAsAttribute
    @XStreamAlias("module")
	private String module;
	@XStreamAsAttribute
    @XStreamAlias("name")
	private String name;
	@XStreamAsAttribute
    @XStreamAlias("version")
	private String version;
	@XStreamAsAttribute
    @XStreamAlias("title")
	private String title;
	@XStreamAsAttribute
    @XStreamAlias("description")
	private String description;

    @XStreamImplicit
    @XStreamAlias("schema")
    private List<Schema> schemaList;

    public ApiConf() {
    }
   
 	 	 
     public Parameters getParameters(){
     	return parameters;
     }

     public void setParameters(Parameters parameters){
     	this.parameters = parameters;
     }
	 	 	 
     public List<Handler> getPrehandlerList(){
     	return prehandlerList;
     }

     public void setPrehandlerList(List<Handler> prehandlerList){
     	this.prehandlerList = prehandlerList;
     }
	 	 	 
     public List<Precheck> getPrecheckList(){
     	return precheckList;
     }

     public void setPrecheckList(List<Precheck> precheckList){
     	this.precheckList = precheckList;
     }
	 	 	 
     public Handlers getHandlers(){
     	return handlers;
     }

     public void setHandlers(Handlers handlers){
     	this.handlers = handlers;
     }
	 	 	 
     public Results getResults(){
     	return results;
     }

     public void setResults(Results results){
     	this.results = results;
     }
	 	 	 
     public String getModule(){
     	return module;
     }

     public void setModule(String module){
     	this.module = module;
     }
	 	 	 
     public String getName(){
     	return name;
     }

     public void setName(String name){
     	this.name = name;
     }
	 	 	 
     public String getVersion(){
     	return version;
     }

     public void setVersion(String version){
     	this.version = version;
     }
	 	 	 
     public String getTitle(){
     	return title;
     }

     public void setTitle(String title){
     	this.title = title;
     }
	 	 	 
     public String getDescription(){
     	return description;
     }

     public void setDescription(String description){
     	this.description = description;
     }

    public List<Schema> getSchemaList() {
        return schemaList;
    }

    public void setSchemaList(List<Schema> schemaList) {
        this.schemaList = schemaList;
    }
}
