package com.hframework.peacock.controller.bean.apiconf;

import com.thoughtworks.xstream.annotations.XStreamAlias;

/**
 * generated by hframework on 2017.
 */@XStreamAlias("response")
public class Response {

    @XStreamAlias("node")
    private Node node;

    public Response() {
    }

    public Node getNode() {
        return node;
    }

    public void setNode(Node node) {
        this.node = node;
    }
}
