package com.hframework.smartweb.bean.apiconf;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;

/**
 * generated by hframework on 2017.
 */@XStreamAlias("checker")
public class Checker   {

	@XStreamAsAttribute
    @XStreamAlias("class")
	private String clazz;
	@XStreamAsAttribute
    @XStreamAlias("pattern")
	private String pattern;

    public Checker() {
    }
   
 	 	 
     public String getClazz(){
     	return clazz;
     }

     public void setClazz(String clazz){
     	this.clazz = clazz;
     }
	 	 	 
     public String getPattern(){
     	return pattern;
     }

     public void setPattern(String pattern){
     	this.pattern = pattern;
     }
	 
}
