package com.hframework.smartweb.bean.apiconf;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;

import java.util.List;

/**
 * generated by hframework on 2017.
 */@XStreamAlias("handlers")
public class Handlers   {

	@XStreamImplicit
    @XStreamAlias("handler")
	private List<Handler> handlerList;

    public Handlers() {
    }
   
 	 	 
     public List<Handler> getHandlerList(){
     	return handlerList;
     }

     public void setHandlerList(List<Handler> handlerList){
     	this.handlerList = handlerList;
     }
	 
}
