package com.hframework.smartweb.bean.apiconf;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import com.thoughtworks.xstream.converters.extended.ToAttributedValueConverter;

/**
 * generated by hframework on 2017.
 */@XStreamAlias("option")
@XStreamConverter(value=ToAttributedValueConverter.class, strings={"text"})
public class Option   {

	@XStreamAsAttribute
    @XStreamAlias("value")
	private String value;
	@XStreamAsAttribute
    @XStreamAlias("default")
	private String defaultValue;
	
	private String text;

    public Option() {
    }
   
 	 	 
     public String getValue(){
     	return value;
     }

     public void setValue(String value){
     	this.value = value;
     }
	 	 	 
     public String getDefaultValue(){
     	return defaultValue;
     }

     public void setDefaultValue(String defaultValue){
     	this.defaultValue = defaultValue;
     }
	 	 	 
     public String getText(){
     	return text;
     }

     public void setText(String text){
     	this.text = text;
     }
	 
}
