package com.hframework.smartweb.bean.apiconf;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;
import com.thoughtworks.xstream.annotations.XStreamImplicit;

import java.util.List;

/**
 * generated by hframework on 2017.
 */@XStreamAlias("parameter")
public class Parameter   {

	@XStreamImplicit
    @XStreamAlias("option")
	private List<Option> optionList;
	@XStreamImplicit
    @XStreamAlias("checker")
	private List<Checker> checkerList;
	@XStreamAlias("parser")
	private Parser parser;
	@XStreamAlias("value")
	private String value;
	@XStreamAsAttribute
    @XStreamAlias("name")
	private String name;
	@XStreamAsAttribute
    @XStreamAlias("type")
	private String type;
	@XStreamAsAttribute
    @XStreamAlias("required")
	private String required;
	@XStreamAsAttribute
    @XStreamAlias("description")
	private String description;
	@XStreamAsAttribute
    @XStreamAlias("enum")
	private String enumClass;
	@XStreamAsAttribute
    @XStreamAlias("default")
	private String defaultValue;
	@XStreamAsAttribute
    @XStreamAlias("min")
	private String min;
	@XStreamAsAttribute
    @XStreamAlias("max")
	private String max;
    @XStreamAsAttribute
    @XStreamAlias("regex")
    private String regex;
	@XStreamAsAttribute
    @XStreamAlias("scope")
	private String scope;
	@XStreamAsAttribute
    @XStreamAlias("ref")
	private String ref;

    public Parameter() {
    }
   
 	 	 
     public List<Option> getOptionList(){
     	return optionList;
     }

     public void setOptionList(List<Option> optionList){
     	this.optionList = optionList;
     }
	 	 	 
     public List<Checker> getCheckerList(){
     	return checkerList;
     }

     public void setCheckerList(List<Checker> checkerList){
     	this.checkerList = checkerList;
     }
	 	 	 
     public Parser getParser(){
     	return parser;
     }

     public void setParser(Parser parser){
     	this.parser = parser;
     }
	 	 	 
     public String getValue(){
     	return value;
     }

     public void setValue(String value){
     	this.value = value;
     }
	 	 	 
     public String getName(){
     	return name;
     }

     public void setName(String name){
     	this.name = name;
     }
	 	 	 
     public String getType(){
     	return type;
     }

     public void setType(String type){
     	this.type = type;
     }
	 	 	 
     public String getRequired(){
     	return required;
     }

     public void setRequired(String required){
     	this.required = required;
     }
	 	 	 
     public String getDescription(){
     	return description;
     }

     public void setDescription(String description){
     	this.description = description;
     }
	 	 	 
     public String getEnumClass(){
     	return enumClass;
     }

     public void setEnumClass(String enumClass){
     	this.enumClass = enumClass;
     }
	 	 	 
     public String getDefaultValue(){
     	return defaultValue;
     }

     public void setDefaultValue(String defaultValue){
     	this.defaultValue = defaultValue;
     }
	 	 	 
     public String getMin(){
     	return min;
     }

     public void setMin(String min){
     	this.min = min;
     }
	 	 	 
     public String getMax(){
     	return max;
     }

     public void setMax(String max){
     	this.max = max;
     }
	 	 	 
     public String getScope(){
     	return scope;
     }

     public void setScope(String scope){
     	this.scope = scope;
     }
	 	 	 
     public String getRef(){
     	return ref;
     }

     public void setRef(String ref){
     	this.ref = ref;
     }

    public String getRegex() {
        return regex;
    }

    public void setRegex(String regex) {
        this.regex = regex;
    }
}
