package com.hframework.smartweb.bean.apiconf;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;
import com.thoughtworks.xstream.annotations.XStreamImplicit;

import java.util.List;

/**
 * generated by hframework on 2017.
 */@XStreamAlias("precheck")
public class Precheck   {

	@XStreamImplicit
    @XStreamAlias("express")
	private List<String> expressList;
	@XStreamAsAttribute
    @XStreamAlias("scope")
	private String scope;
	@XStreamAsAttribute
    @XStreamAlias("class")
	private String clazz;
	@XStreamAsAttribute
    @XStreamAlias("pass")
	private String pass;
	@XStreamAsAttribute
    @XStreamAlias("unpass")
	private String unpass;
	@XStreamAsAttribute
    @XStreamAlias("unpass_result")
	private String unpassResult;

    public Precheck() {
    }
   
 	 	 
     public List<String> getExpressList(){
     	return expressList;
     }

     public void setExpressList(List<String> expressList){
     	this.expressList = expressList;
     }
	 	 	 
     public String getScope(){
     	return scope;
     }

     public void setScope(String scope){
     	this.scope = scope;
     }
	 	 	 
     public String getClazz(){
     	return clazz;
     }

     public void setClazz(String clazz){
     	this.clazz = clazz;
     }
	 	 	 
     public String getPass(){
     	return pass;
     }

     public void setPass(String pass){
     	this.pass = pass;
     }
	 	 	 
     public String getUnpass(){
     	return unpass;
     }

     public void setUnpass(String unpass){
     	this.unpass = unpass;
     }
	 	 	 
     public String getUnpassResult(){
     	return unpassResult;
     }

     public void setUnpassResult(String unpassResult){
     	this.unpassResult = unpassResult;
     }
	 
}
