package com.hframework.smartweb.bean.apiconf;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;
import com.thoughtworks.xstream.annotations.XStreamImplicit;

import java.util.List;

/**
 * generated by hframework on 2017.
 */@XStreamAlias("prehandler")
public class Prehandler   {

	@XStreamImplicit
    @XStreamAlias("result")
	private List<Result> resultList;
	@XStreamAsAttribute
    @XStreamAlias("id")
	private String id;
	@XStreamAsAttribute
    @XStreamAlias("class")
	private String clazz;

    public Prehandler() {
    }
   
 	 	 
     public List<Result> getResultList(){
     	return resultList;
     }

     public void setResultList(List<Result> resultList){
     	this.resultList = resultList;
     }
	 	 	 
     public String getId(){
     	return id;
     }

     public void setId(String id){
     	this.id = id;
     }
	 	 	 
     public String getClazz(){
     	return clazz;
     }

     public void setClazz(String clazz){
     	this.clazz = clazz;
     }
	 
}
