package com.hframework.client.decrypt;

import com.hframework.common.helper.Rules;
import com.hframework.common.util.security.*;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * generated by hframework on 2018.
 */
public class DecryptHelper   {

	
	public static String getCurTimestamp()  throws Exception{
			SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
			String time=df.format(new Date());
			return time;
	}

	
	public static String sign(String timestamp)  throws Exception{
			return MD5Util.encrypt(DecryptConfig.getInstance().getKey() + timestamp + DecryptConfig.getInstance().getClient() + DecryptConfig.getInstance().getKey()).toUpperCase();
	}

  
 
}
